# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DzyCollection' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DzyCollection
pod 'AFNetworking', '~> 3.1.0'
  target 'DzyCollectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DzyCollectionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
